[platformio]
default_envs = esp32-benny

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+
lib_deps =
  bblanchon/ArduinoJson@^7.4.2
  arduino-libraries/ArduinoMqttClient@^0.1.8
  chris--a/Keypad@^3.1.1
  marcoschwartz/LiquidCrystal_I2C@^1.1.4
  tzapu/WiFiManager@^2.0.17

[env:esp32-benny]
board = esp32dev
build_flags = -D TAMBOX_HARDWARE_PROFILE=1

[env:esp32-s3]
board = esp32-s3-devkitc-1
build_flags = -D TAMBOX_HARDWARE_PROFILE=2

[env:esp32-classic-safe]
board = esp32dev
build_flags = -D TAMBOX_HARDWARE_PROFILE=3
