[platformio]
default_envs = esp32-benny-check

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+
lib_deps =
  chris--a/Keypad@^3.1.1
  marcoschwartz/LiquidCrystal_I2C@^1.1.4

[env:esp32-benny-check]
board = esp32dev
build_flags = -D TMBOX_HARDWARE_PROFILE=1

[env:esp32-classic-safe-check]
board = esp32dev
build_flags = -D TMBOX_HARDWARE_PROFILE=3

[env:esp32-s3-check]
board = esp32-s3-devkitc-1
build_flags = -D TMBOX_HARDWARE_PROFILE=2
